### PR TITLE
Update to upstream 2

### PR DESCRIPTION
**Pull request by Istador**
Relevant changes in this merge that (might) affect the servers view in this fork:
- 4927936f259d52dc872c2e0ff8d0f09626dda01e
- 51d48054afa22c2fdb43fedc4cac49a5daf1af56
- aaeeb465d44964264d7c43558cbc9f4b07d74803
- d54f721d20ef0201ee3f9f1e2299f3bd2042259e
- eb910bca74ece94eec65a8b23e8f98bfe65b9c86
- cf9f9efa3acc6ddb011b9df87927320d883cc90f
- 9e8cbafbf5a30627dcbaf0852e809d4119b0d7b4
- bdac880ed9dca65740e9d3f4832acf8265de2e3a
- 27c3ff996b300d2fc425047a3760d8a584ac35ff
- fb8f3cf3df82e86d518e6f82d933c902b0deb8ed
- 4866648293cab37a5aa9dbfc877f6ebde275aa39
- 67eea081e82addd6ecc692568a1afb51e35f30e5
- ceb3d75ed346379304f9834790d2f67705a409f3
- 0f08ea50723af00831d65abec2d0dbd288333fa3
- efee46d17667a1ed89749de6f90a5eb1e1d6f3f1

Note: the [api](https://github.com/Istador/smoo.it/tree/api) branch was [changed](https://github.com/Istador/smoo.it/compare/537d4849bb56a67f06fc64b243669a370e2ad1ea...api) a bit too. You might want to update that on the server also and configure the API token. (These changes should be backwards compatible and work with older API versions. Though not the other way around: update the website before the API.)

### CODE REVIEW

**Review by piplup55 — APPROVED** [review]

**Comment by piplup55** [comment]
while i did approve this it does throw some compile errors on my end i don't think these will cause issues thought it should be mentioned
[smooit.log](https://github.com/TeamPiplup/smoo.it/files/11780467/ah.txt)

**Comment by Istador** [comment]
Interesting I don't had any errors and the workflow also doesn't have them in its [log](https://github.com/Istador/smoo.it/actions/runs/5284615311/jobs/9562224123).

From my perspective this might be either because of a newer node version on your end (the workflow uses node 16)
or by missing dependency installation via `npm install --legacy-peer-deps` (or alternatively with `npm ci` to only install exactly what is in the lock file and nothing else).

From the error messages in the log it seems like the dependencies are missing.

---

Working in my development VM:

```bash
$ git checkout TeamPiplup/public 
warning: refname 'TeamPiplup/public' is ambiguous.
Already on 'TeamPiplup/public'
Your branch is up to date with 'istador/TeamPiplup/public'.
$ rm -rf node_modules/
$ rm -rf dist/
$ node --version
v16.20.0
$ npm --version
8.19.4
$ npm install --legacy-peer-deps
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

added 1084 packages, and audited 1085 packages in 13s

152 packages are looking for funding
  run `npm fund` for details

1 high severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
$ npm run build

> smoo.it@0.1.0 build
> vue-cli-service build

All browser targets in the browserslist configuration have supported ES module.
Therefore we don't build two separate bundles for differential loading.


⠧  Building for production...

 WARNING  Compiled with 3 warnings                                                                          2:53:23 PM

 warning  

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  js/chunk-vendors.781b3d44.js (2.07 MiB)

 warning  

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  index (2.34 MiB)
      js/chunk-vendors.781b3d44.js
      css/index.fd6f5f01.css
      js/index.bd793e03.js


 warning  

webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

  File                                 Size                                  Gzipped

  dist/js/chunk-vendors.781b3d44.js    2124.08 KiB                           681.69 KiB
  dist/js/index.bd793e03.js            40.83 KiB                             11.81 KiB
  dist/css/index.fd6f5f01.css          232.29 KiB                            34.76 KiB

  Images and other types of assets omitted.
  Build at: 2023-06-18T12:53:24.068Z - Hash: 26c2f4d60ff98517 - Time: 40479ms

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
```

**Comment by TheUbMunster** [comment]
npm is always flakey rip. looks good!

**Review by TheUbMunster — APPROVED** [review]

**Comment by piplup55** [comment]
seems to deploy fine on https://piplup.smoo.it/ merging

**Comment by Istador** [comment]
Hmm, there seems to be a 404 on https://piplup.smoo.it/api/servers.json now.

**Comment by Istador** [comment]
If you also updated the `api`, then you might be missing `mod_rewrite` for:
https://github.com/Istador/smoo.it/blob/8b9822824a070922c429bcbdd0107a1e4f674899/html/.htaccess#L3-L8

You can enable it with:
```sh
sudo a2enmod rewrite
```

**Pull request merged**
